# Generated by Django 5.2.7 on 2025-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=200)),
                ('objective', models.CharField(max_length=255)),
                ('thematic', models.CharField(max_length=50)),
                ('directorate', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
