# Generated by Django 5.2.7 on 2025-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='objective',
            field=models.CharField(max_length=500),
        ),
    ]
