# Generated by Django 5.2.7 on 2025-11-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='directorate',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='thematic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
